apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-cicd
  labels:
    app: hello-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-cicd
  template:
    metadata:
      labels:
        app: hello-cicd
    spec:
      containers:
      - name: hello-cicd
        image: gcr.io/<PROJECT_ID>/cicd-image:234c071
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hello-cicd
spec:
  selector:
    app: hello-cicd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer